repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: pretty-format-json
        args: [--autofix]
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch, master, --branch, main --verbose]
  - repo: https://github.com/crate-ci/typos
    rev: v1.23.1
    hooks:
      - id: typos
        args: [--verbose]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [--verbose]
