DB_ENGINE = "SQLite"
TABLES = ["airlines", "airports", "flights"]
SCHEMA = """
Database Schema:
- airlines (IATA_CODE, AIRLINE)
- airports (IATA_CODE, AIRPORT, CITY, STATE, COUNTRY, LATITUDE, LONGITUDE)
- flights (
    YEAR, MONTH, DAY, DAY_OF_WEEK, AIRLINE, FLIGHT_NUMBER, TAIL_NUMBER,
    ORIGIN_AIRPORT, DESTINATION_AIRPORT, SCHEDULED_DEPARTURE, DEPARTURE_TIME,
    DEPARTURE_DELAY, TAXI_OUT, WHEELS_OFF, SCHEDULED_TIME, ELAPSED_TIME,
    AIR_TIME, DISTANCE, WHEELS_ON, TAXI_IN, SCHEDULED_ARRIVAL, ARRIVAL_TIME,
    ARRIVAL_DELAY, DIVERTED, CANCELLED, CANCELLATION_REASON,
    AIR_SYSTEM_DELAY, SECURITY_DELAY, AIRLINE_DELAY, LATE_AIRCRAFT_DELAY,
    WEATHER_DELAY
)

Table Relationships:
- airlines.IATA_CODE = flights.AIRLINE
- airports.IATA_CODE = flights.ORIGIN_AIRPORT
- airports.IATA_CODE = flights.DESTINATION_AIRPORT
"""
